config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notifications

  resources :conditions

  resources :buhins

  resources :syaryos

  resources :jikkens do
    collection { post :import }
  end

 root to: redirect( '/jikkens' )

end

app/models/syaryo.rb
# == Schema Information
#
# Table name: syaryos
#
#  id            :integer          not null, primary key
#  number_plate  :string(255)
#  keeping_place :string(255)
#  condition_id  :integer
#  memo          :text
#  status        :integer
#  jikken_id     :integer
#  created_at    :datetime
#  updated_at    :datetime
#  deadline      :date
#

class Syaryo < ActiveRecord::Base
  belongs_to :jikken
  belongs_to :condition

  def self.warning?
   self.where(["deadline < ? ", Date.today]).count > 0
  end

end

app/controllers/syaryos_controller.rb
class SyaryosController < ApplicationController
  before_action :set_syaryo, only: [:show, :edit, :update, :destroy]

  # GET /syaryos
  # GET /syaryos.json
  def index
    @syaryos = Syaryo.all
  end

  # GET /syaryos/1
  # GET /syaryos/1.json
  def show
  end

  # GET /syaryos/new
  def new
    @syaryo = Syaryo.new
  end

  # GET /syaryos/1/edit
  def edit
  end

  # POST /syaryos
  # POST /syaryos.json
  def create
    @syaryo = Syaryo.new(syaryo_params)

    respond_to do |format|
      if @syaryo.save
        format.html { redirect_to @syaryo, notice: 'Syaryo was successfully created.' }
        format.json { render :show, status: :created, location: @syaryo }
      else
        format.html { render :new }
        format.json { render json: @syaryo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /syaryos/1
  # PATCH/PUT /syaryos/1.json
  def update
    respond_to do |format|
      if @syaryo.update(syaryo_params)
        format.html { redirect_to @syaryo, notice: 'Syaryo was successfully updated.' }
        format.json { render :show, status: :ok, location: @syaryo }
      else
        format.html { render :edit }
        format.json { render json: @syaryo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /syaryos/1
  # DELETE /syaryos/1.json
  def destroy
    @syaryo.destroy
    respond_to do |format|
      format.html { redirect_to syaryos_url, notice: 'Syaryo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_syaryo
      @syaryo = Syaryo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def syaryo_params
      params.require(:syaryo).permit(:number_plate, :keeping_place, :condition_id, :memo, :status, :jikken_id,  :deadline)
    end
end

app/helpers/syaryos_helper.rb
module SyaryosHelper
end

app/views/syaryos/_form.html.erb
<%= form_for(@syaryo) do |f| %>
  <% if @syaryo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@syaryo.errors.count, "error") %> prohibited this syaryo from being saved:</h2>

      <ul>
      <% @syaryo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number_plate %><br>
    <%= f.text_field :number_plate %>
  </div>
  <div class="field">
    <%= f.label :keeping_place %><br>
    <%= f.text_field :keeping_place %>
  </div>
  <div class="field">
    <%= f.label :condition_id %><br>
    <%= f.collection_select( :condition_id, Condition.all, :id, :name, :include_blank => true ) %>
  </div>

  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline %>
  </div>

  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_area :memo %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :jikken_id %><br>
    <%= f.number_field :jikken_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/syaryos/_index.html.erb
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>ナンバープレート</th>
      <th>Keeping place</th>
      <th>Condition</th>
      <th>保管期限</th>
      <th>Memo</th>
      <th>Status</th>
      <th>Jikken</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @syaryos.each do |syaryo| %>
    <% if syaryo.deadline.present? and syaryo.deadline < Date.today %>
      <tr class="warning_color">
    <% else %>
      <tr>
    <% end %>
        <td><%= syaryo.number_plate %></td>
        <td><%= syaryo.keeping_place %></td>
        <td><%= syaryo.condition.name %></td>
        <td><%= syaryo.deadline %></td>
        <td><%= syaryo.memo %></td>
        <td><%= syaryo.status %></td>
        <td><%= syaryo.jikken_id %></td>
        <td><%= link_to 'Show', syaryo %></td>
        <td><%= link_to 'Edit', edit_syaryo_path(syaryo) %></td>
        <td><%= link_to 'Destroy', syaryo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/syaryos/edit.html.erb
<h1>Editing syaryo</h1>

<%= render 'form' %>

<%= link_to 'Show', @syaryo %> |
<%= link_to 'Back', syaryos_path %>

app/views/syaryos/index.html.erb
<h1>車両一覧</h1>

<%= render 'index' %>
<br>

<%= link_to 'New Syaryo', new_syaryo_path %>

app/views/syaryos/new.html.erb
<h1>New syaryo</h1>

<%= render 'form' %>

<%= link_to 'Back', syaryos_path %>

app/views/syaryos/show.html.erb
<p>
  <strong>Number plate:</strong>
  <%= @syaryo.number_plate %>
</p>

<p>
  <strong>Keeping place:</strong>
  <%= @syaryo.keeping_place %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @syaryo.condition.name %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @syaryo.deadline %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @syaryo.memo %>
</p>

<p>
  <strong>Status:</strong>
  <%= @syaryo.status %>
</p>

<p>
  <strong>Jikken:</strong>
  <%= @syaryo.jikken_id %>
</p>

<%= link_to 'Edit', edit_syaryo_path(@syaryo) %> |
<%= link_to 'Back', syaryos_path %>