config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notifications

  resources :conditions

  resources :buhins

  resources :syaryos

  resources :jikkens do
    collection { post :import }
  end

 root to: redirect( '/jikkens' )

end

app/models/buhin.rb
# == Schema Information
#
# Table name: buhins
#
#  id         :integer          not null, primary key
#  hinmei     :string(255)
#  hinban     :string(255)
#  nouhin_sya :string(255)
#  nouhin_day :datetime
#  tantou     :string(255)
#  kosu       :integer
#  jikken_id  :integer
#  created_at :datetime
#  updated_at :datetime
#  deadline   :date
#

class Buhin < ActiveRecord::Base
  belongs_to :jikken
end

app/controllers/buhins_controller.rb
class BuhinsController < ApplicationController
  before_action :set_buhin, only: [:show, :edit, :update, :destroy]

  # GET /buhins
  # GET /buhins.json
  def index
    @buhins = Buhin.all
  end

  # GET /buhins/1
  # GET /buhins/1.json
  def show
  end

  # GET /buhins/new
  def new
    @buhin = Buhin.new
  end

  # GET /buhins/1/edit
  def edit
  end

  # POST /buhins
  # POST /buhins.json
  def create
    @buhin = Buhin.new(buhin_params)

    respond_to do |format|
      if @buhin.save
        format.html { redirect_to @buhin, notice: 'Buhin was successfully created.' }
        format.json { render :show, status: :created, location: @buhin }
      else
        format.html { render :new }
        format.json { render json: @buhin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buhins/1
  # PATCH/PUT /buhins/1.json
  def update
    respond_to do |format|
      if @buhin.update(buhin_params)
        format.html { redirect_to @buhin, notice: 'Buhin was successfully updated.' }
        format.json { render :show, status: :ok, location: @buhin }
      else
        format.html { render :edit }
        format.json { render json: @buhin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buhins/1
  # DELETE /buhins/1.json
  def destroy
    @buhin.destroy
    respond_to do |format|
      format.html { redirect_to buhins_url, notice: 'Buhin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buhin
      @buhin = Buhin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buhin_params
      params.require(:buhin).permit(:hinmei, :hinban, :nouhin_sya, :nouhin_day, :tantou, :kosu, :jikken_id, :deadline)
    end
end

app/helpers/buhins_helper.rb
module BuhinsHelper
end

app/views/buhins/_form.html.erb
<%= form_for(@buhin) do |f| %>
  <% if @buhin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buhin.errors.count, "error") %> prohibited this buhin from being saved:</h2>

      <ul>
      <% @buhin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.hidden_field :jikken_id %>

  <div class="field">
    <%= f.label :hinmei %><br>
    <%= f.text_field :hinmei %>
  </div>
  <div class="field">
    <%= f.label :hinban %><br>
    <%= f.text_field :hinban %>
  </div>
  <div class="field">
    <%= f.label :nouhin_sya %><br>
    <%= f.text_field :nouhin_sya %>
  </div>
  <div class="field">
    <%= f.label :nouhin_day %><br>
    <%= f.datetime_select :nouhin_day %>
  </div>
  <div class="field">
    <%= f.label :tantou %><br>
    <%= f.text_field :tantou %>
  </div>
  <div class="field">
    <%= f.label :kosu %><br>
    <%= f.text_field :kosu %>
  </div>
  <div class="field">
    <%= f.label :jikken_id %><br>
    <%= f.number_field :jikken_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buhins/_index.html.erb
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Hinmei</th>
      <th>Hinban</th>
      <th>Nouhin sya</th>
      <th>Nouhin day</th>
      <th>Tantou</th>
      <th>Kosu</th>
      <th>Jikken</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buhins.each do |buhin| %>
      <tr>
        <td><%= buhin.hinmei %></td>
        <td><%= buhin.hinban %></td>
        <td><%= buhin.nouhin_sya %></td>
        <td><%= buhin.nouhin_day %></td>
        <td><%= buhin.tantou %></td>
        <td><%= buhin.kosu %></td>
        <td><%= buhin.jikken_id %></td>
        <td><%= link_to 'Show', buhin %></td>
        <td><%= link_to 'Edit', edit_buhin_path(buhin) %></td>
        <td><%= link_to 'Destroy', buhin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/buhins/edit.html.erb
<h1>Editing buhin</h1>

<%= render 'form' %>

<%= link_to 'Show', @buhin %> |
<%= link_to 'Back', buhins_path %>

app/views/buhins/index.html.erb
<h1>部品一覧</h1>

<%= render 'index' %>

<br>

<%= link_to 'New Buhin', new_buhin_path %>

app/views/buhins/new.html.erb
<h1>New buhin</h1>

<%= render 'form' %>

<%= link_to 'Back', buhins_path %>

app/views/buhins/show.html.erb
<p>
  <strong>Hinmei:</strong>
  <%= @buhin.hinmei %>
</p>

<p>
  <strong>Hinban:</strong>
  <%= @buhin.hinban %>
</p>

<p>
  <strong>Nouhin sya:</strong>
  <%= @buhin.nouhin_sya %>
</p>

<p>
  <strong>Nouhin day:</strong>
  <%= @buhin.nouhin_day %>
</p>

<p>
  <strong>Tantou:</strong>
  <%= @buhin.tantou %>
</p>

<p>
  <strong>Kosu:</strong>
  <%= @buhin.kosu %>
</p>

<p>
  <strong>Jikken:</strong>
  <%= @buhin.jikken_id %>
</p>

<%= link_to 'Edit', edit_buhin_path(@buhin) %> |
<%= link_to 'Back', buhins_path %>