config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notifications

  resources :conditions

  resources :buhins

  resources :syaryos

  resources :jikkens do
    collection { post :import }
  end

 root to: redirect( '/jikkens' )

end

app/models/jikken.rb
# == Schema Information
#
# Table name: jikkens
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  plan_start :datetime
#  plan_end   :datetime
#  act_start  :datetime
#  act_end    :datetime
#  memo       :text
#  created_at :datetime
#  updated_at :datetime
#  tantou     :string(255)
#  deadline   :date
#

class Jikken < ActiveRecord::Base
  has_many :buhins
  has_many :syaryos

  def self.import(file)
#    CSV.foreach(file.path, headers: true) do |row|
#      Jikken.create! row.to_hash
#    end

    CSV.foreach(file.path, headers: true) do |row|
      jikken = find_by_id(row["id"]) || new
      jikken.attributes = row.to_hash.slice(*Jikken.attribute_names()) # Rails4ではこの書き方になるとのこと
      jikken.save!
    end
  
  end
  
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |jikken|
        csv << jikken.attributes.values_at(*column_names)
      end
    end
  end


  #予定の実験数を取得（引数；date型、dateの前２ヶ月、当月、後９ヶ月のデータを作成）
  def self.count_yotei_exp(date)
  	result = Array.new
    for i in 1 .. 12 do
      result.push(Jikken.where(["plan_start <= ? and plan_end >= ?", 
      	                         (date>>i-3).end_of_month,
      	                         (date>>i-3).beginning_of_month]).count)
  	end
    return result
  end

  #実績の実験数を取得（引数；date型、dateの前２ヶ月、当月、後９ヶ月のデータを作成）
  def self.count_jisseki_exp(date)
  	result = Array.new
    for i in 1 .. 12 do
      result.push(Jikken.where(["act_start <= ? and act_end >= ?", 
      	                         (date>>i-3).end_of_month,
      	                         (date>>i-3).beginning_of_month]).count)
  	end
    return result
  end

  #グラフ用のラベルを作成（引数；date型、dateの前２ヶ月、当月、後９ヶ月のラベルを作成）
  def self.graph_label(date)
  	result = Array.new
    for i in 1 .. 12 do
      result.push((date>>i-3).strftime("%Y/%m").to_s) 
    end
    return result
  end


end

app/controllers/jikkens_controller.rb
class JikkensController < ApplicationController
  before_action :set_jikken, only: [:show, :edit, :update, :destroy]

  # GET /jikkens
  # GET /jikkens.json
  def index

    date = Date.today
    @search = Jikken.search(params[:q])
    @jikkens = @search.result.page params[:page]

    @yotei = Jikken.count_yotei_exp(date)
    @jisseki = Jikken.count_jisseki_exp(date)
    @label_dat = Jikken.graph_label(date)

    #csv.sho
    respond_to do |format|
      format.html
      format.csv { send_data @jikkens.to_csv }
    end

  end

  # GET /jikkens/1
  # GET /jikkens/1.json
  def show
    @syaryos = @jikken.syaryos.all
    @syaryo  = @jikken.syaryos.build
    @buhins = @jikken.buhins.all
    @buhin  = @jikken.buhins.build
  end

  # GET /jikkens/new
  def new
    @jikken = Jikken.new
  end

  # GET /jikkens/1/edit
  def edit
  end

  # POST /jikkens
  # POST /jikkens.json
  def create
    @jikken = Jikken.new(jikken_params)

    respond_to do |format|
      if @jikken.save
        format.html { redirect_to @jikken, notice: 'Jikken was successfully created.' }
        format.json { render :show, status: :created, location: @jikken }
      else
        format.html { render :new }
        format.json { render json: @jikken.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jikkens/1
  # PATCH/PUT /jikkens/1.json
  def update
    respond_to do |format|
      if @jikken.update(jikken_params)
        format.html { redirect_to @jikken, notice: 'Jikken was successfully updated.' }
        format.json { render :show, status: :ok, location: @jikken }
      else
        format.html { render :edit }
        format.json { render json: @jikken.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jikkens/1
  # DELETE /jikkens/1.json
  def destroy
    @jikken.destroy
    respond_to do |format|
      format.html { redirect_to jikkens_url, notice: 'Jikken was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # csv の読み込み
  def import
    Jikken.import(params[:file])
    redirect_to action: "index", notice: "Jikkens imported."
  end

  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jikken
      @jikken = Jikken.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jikken_params
      params.require(:jikken).permit(:title, :plan_start, :plan_end, :act_start, :act_end, :memo, :tantou, :deadline)
    end
end

app/helpers/jikkens_helper.rb
module JikkensHelper
end

app/views/jikkens/_form.html.erb
<%= form_for(@jikken) do |f| %>
  <% if @jikken.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jikken.errors.count, "error") %> prohibited this jikken from being saved:</h2>

      <ul>
      <% @jikken.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :tantou %><br>
    <%= f.text_field :tantou %>
  </div>
  <div class="field">
    <%= f.label :plan_start %><br>
    <%= f.datetime_select :plan_start %>
  </div>
  <div class="field">
    <%= f.label :plan_end %><br>
    <%= f.datetime_select :plan_end %>
  </div>
  <div class="field">
    <%= f.label :act_start %><br>
    <%= f.datetime_select :act_start %>
  </div>
  <div class="field">
    <%= f.label :act_end %><br>
    <%= f.datetime_select :act_end %>
  </div>

  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_area :memo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jikkens/edit.html.erb
<h1>Editing jikken</h1>

<%= render 'form' %>

<%= link_to 'Show', @jikken %> |
<%= link_to 'Back', jikkens_path %>

app/views/jikkens/index.html.erb
<h1>実験一覧</h1>


<div class="well well-sm">
 【検索条件】
<%= search_form_for @search do |f| %>
  <div>
    <%= f.label :title_cont, 'タイトル' %>
    <%= f.text_field :title_cont %>
  </div>

  <div>
    <%= f.label :created_at, '開始（計画）' %>
    <%= f.date_select :plan_start_gteq, include_blank: true %>〜
    <%= f.date_select :plan_start_lteq_end_of_day, include_blank: true %>
  </div>
  <div>
    <%= f.label :created_at, '終了（計画）' %>
    <%= f.date_select :plan_end_gteq, include_blank: true %>〜
    <%= f.date_select :plan_end_lteq_end_of_day, include_blank: true %>
  </div>
  <br>
  <div>
    <%= f.submit '検索' %>
  </div>
<% end %>
</div>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>名称</th>
      <th>担当者</th>
      <th>開始(計画)</th>
      <th>終了(計画)</th>
      <th>開始(実績)</th>
      <th>終了(実績)</th>
      <th>備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jikkens.each do |jikken| %>
      <tr>
        <td><%= jikken.title %></td>
        <td><%= jikken.tantou %></td>
        <td><%= jikken.plan_start.strftime("%Y/%m/%d") if jikken.plan_start.present? %></td>
        <td><%= jikken.plan_end.strftime("%Y/%m/%d") if jikken.plan_end.present? %></td>
        <td><%= jikken.act_start.strftime("%Y/%m/%d") if jikken.act_start.present? %></td>
        <td><%= jikken.act_end.strftime("%Y/%m/%d") if jikken.act_end.present? %></td>
        <td><%= jikken.memo %></td>
        <td><%= link_to 'Show', jikken %></td>
        <td><%= link_to 'Edit', edit_jikken_path(jikken) %></td>
        <td><%= link_to 'Destroy', jikken, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @jikkens %>

<br>

<%= link_to '新規追加', new_jikken_path %>

<hr>
<div>
 <h3>実験スケジュール</h3>
</div>

<div id="ganttChart"></div>
<script>
$(function() {
  $("#ganttChart").ganttView({ 
    data: ganttData,
    slideWidth: 900
  });
});
//ここからデータ（別ファイル化でもOK）
var ganttData = [
    <% i = 0 %>
    <% @jikkens.each do |jikken| %>
    <% i = i + 1 %>
  {
    id: <%= i %> , name: "<%= jikken.title %>",
     series: [
      { name: "予定", start: "<%= jikken.plan_start.strftime("%Y/%m/%d") if jikken.plan_start.present? %>", end: "<%= jikken.plan_end.strftime("%Y/%m/%d") if jikken.plan_end.present? %>",color: "#EEAAAA" },
      { name: "実績", start: "<%= jikken.act_start.strftime("%Y/%m/%d") if jikken.act_start.present? %>", end: "<%= jikken.act_end.strftime("%Y/%m/%d") if jikken.act_end.present?  %>",color: "#AAAAFF" }
    ]
  },
    <% end %>

];
</script>



<hr>
<div>
 <h3>実験予定・実績グラフ</h3>
</div>

<canvas id="myChart" width="700" height="500"></canvas>
<script>
var data = {
    labels: <%= raw(@label_dat) %> ,
    datasets: [
        {
            label: "予定",
            fillColor: "rgba(220,220,220,0.5)",
            strokeColor: "rgba(220,220,220,0.8)",
            highlightFill: "rgba(220,220,220,0.75)",
            highlightStroke: "rgba(220,220,220,1)",
            data: <%= @yotei %>
        },
        {
            label: "実績",
            fillColor: "rgba(151,187,205,0.5)",
            strokeColor: "rgba(151,187,205,0.8)",
            highlightFill: "rgba(151,187,205,0.75)",
            highlightStroke: "rgba(151,187,205,1)",
            data: <%= @jisseki %>
        }
    ]
};

var options = {
    scaleOverride : true,
    scaleSteps : 10,
    scaleStepWidth : 5,
    scaleStartValue : 0
}


var ctx = document.getElementById("myChart").getContext("2d");
var myBarChart = new Chart(ctx).Bar(data,options);
</script>


<hr>
<h4>実験リストのcsvアップロード</h4>
<%= form_tag import_jikkens_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<hr>
<h4>実験リストのcsvダウンロード</h4>
<%= link_to "CSV", jikkens_path(format: "csv") %>

app/views/jikkens/new.html.erb
<h1>New jikken</h1>

<%= render 'form' %>

<%= link_to 'Back', jikkens_path %>

app/views/jikkens/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @jikken.title %>
</p>

<p>
  <strong>Tantou:</strong>
  <%= @jikken.tantou %>
</p>

<p>
  <strong>Plan start:</strong>
  <%= @jikken.plan_start %>
</p>

<p>
  <strong>Plan end:</strong>
  <%= @jikken.plan_end %>
</p>

<p>
  <strong>Act start:</strong>
  <%= @jikken.act_start %>
</p>

<p>
  <strong>Act end:</strong>
  <%= @jikken.act_end %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @jikken.memo %>
</p>

<hr>
<h3>車両</h3>
<%= render 'syaryos/index' %>

<hr>
<h3>部品</h3>
<%= render 'buhins/index' %>

<hr>
<%= link_to 'Edit', edit_jikken_path(@jikken) %> |
<%= link_to 'Back', jikkens_path %>